---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sparkoperator-crb
  labels:
    app.kubernetes.io/name: sparkoperator
subjects:
  - kind: ServiceAccount
    name: sparkoperator
    namespace: spark-operator
roleRef:
  kind: ClusterRole
  name: sparkoperator-cr
  apiGroup: rbac.authorization.k8s.io

