apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- service-account.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- deployment.yaml
- service.yaml
- job.yaml
- crds.yaml
commonLabels:
  app: spark-operator
  kustomize.component: spark-operator