apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: tpcds-benchmark-1t
  namespace: default
spec:
  type: Scala
  mode: cluster
  sparkVersion: 2.4.5-SNAPSHOT
  image: seedjeffwan/spark:2.4.5-SNAPSHOT-examples
  mainClass: com.amazonaws.eks.tpcds.BenchmarkSparkSQL
  mainApplicationFile: local:///opt/spark/examples/jars/eks-spark-examples-assembly-1.0.jar
  arguments:
  # working directory where data table reside (must exists and have tables directly)
    - "s3a://spark-k8s-data/TPCDS-TEST-1T"
  # location to store results
    - "s3a://spark-k8s-data/TPCDS-TEST-1T-RESULT"
  # Path to kit in the docker image
    - "/opt/tpcds-kit/tools"
  # Scale factor (in GB)
    - "1000"
  # Number of iterations
    - "1"
  # Optimize queries
    - "false"
  # Filter queries, will run all if empty - "q23a-v2.4,q23b-v2.4"
    - ""
  # Logging set to WARN
    - "true"
  sparkConf:
    # Cloud specific - need to run with speculation to avoid strugglers
    "spark.speculation": "false"
    "spark.speculation.multiplier": "3"
    "spark.speculation.quantile": "0.9"
    # TPCDs Specific
    "spark.sql.broadcastTimeout": "7200"
    "spark.sql.crossJoin.enabled": "true"
    "spark.sql.parquet.mergeSchema": "false"
    "spark.sql.parquet.filterPushdown": "true"
    # S3 credential
    "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.InstanceProfileCredentialsProvider"
    # S3 Specific config (remove if s3 not used)
    # We need it to speed up uploads, and outputcommiter/parquet to have consistent writes due to speculation
    "spark.hadoop.fs.s3a.connection.timeout": "1200000"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.connection.maximum": "200"
    "spark.hadoop.fs.s3a.fast.upload": "true"
    # S3A Committer bridge
    "spark.hadoop.mapreduce.outputcommitter.factory.scheme.s3a": "org.apache.hadoop.fs.s3a.commit.S3ACommitterFactory"
    # "spark.sql.sources.commitProtocolClass": "org.apache.spark.internal.io.cloud.PathOutputCommitProtocol"
    # "spark.sql.parquet.output.committer.class": "org.apache.hadoop.mapreduce.lib.output.BindingPathOutputCommitter"
    # Magic Committer
    # "spark.hadoop.fs.s3a.committer.name": "magic"
    # "spark.hadoop.fs.s3a.committer.magic.enabled": "true"
    # "spark.hadoop.fs.s3a.metadatastore.impl": "org.apache.hadoop.fs.s3a.s3guard.DynamoDBMetadataStore"
    # "spark.hadoop.fs.s3a.s3guard.ddb.region": "us-west-2"
    # "spark.hadoop.fs.s3a.s3guard.ddb.table.create": "true"
    # Staging Committer
    "spark.hadoop.fs.s3a.committer.name": "directory"
    "spark.hadoop.fs.s3a.committer.staging.conflict-mode": "append"
  driver:
    cores: 6
    coreLimit: "6144m"
    memory: "8000m"
    serviceAccount: spark
  executor:
    instances: 90
    cores: 1
    memory: "8000m"
    memoryOverhead: "2g"
  restartPolicy:
    type: Never
