apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-history-server
  labels:
    app.kubernetes.io/name: spark-history-server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-history-server-cr
  labels:
    app.kubernetes.io/name: spark-history-server
rules:
- apiGroups: [""]
  resources: ["deployments", "pods"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-history-server-crb
subjects:
- kind: ServiceAccount
  name: spark-history-server
  namespace: default
roleRef:
  kind: ClusterRole
  name: spark-history-server-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  labels:
    app.kubernetes.io/name: spark-history-server
spec:
  type: ClusterIP
  ports:
  - port: 18080
    protocol: TCP
  selector:
    app.kubernetes.io/name: spark-history-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  labels:
    app.kubernetes.io/name: spark-history-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-history-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-history-server
    spec:
      serviceAccountName: spark-history-server
      containers:
      - name: spark-history-server
        image: "seedjeffwan/spark:2.4.5-SNAPSHOT-s3"
        imagePullPolicy: IfNotPresent
        env:
        - name: SPARK_NO_DAEMONIZE
          value: "false"
        - name: SPARK_HISTORY_OPTS
          value: "-Dspark.history.fs.logDirectory=s3a://spark-eks/spark-history-server/ -Dspark.hadoop.fs.s3a.secret.key=AKIA2CURGJTGXY53Y5HQ -Dspark.hadoop.fs.s3a.access.key=gvbsfEQcowWBiFeRx4Qz8ga5LVDtuWQJpzxdi+aA"
        ports:
        - containerPort: 18080
        resources:
          {}
        command:
        - /opt/spark/sbin/start-history-server.sh
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
