apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi-prometheus
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "seedjeffwan/spark:2.4.5-SNAPSHOT-prometheus"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  # mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.3.jar"
  mainApplicationFile: "local:///opt/spark/examples/target/original-spark-examples_2.11-2.4.5-SNAPSHOT.jar"
  arguments:
    - "100000"
  sparkVersion: "2.4.5-SNAPSHOT"
  restartPolicy:
    type: Never
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    serviceAccount: spark
  executor:
    cores: 1
    instances: 10
    memory: "512m"
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.12.0.jar"
      port: 8090