apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "seedjeffwan/spark:3.0.0-SNAPSHOT"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0-SNAPSHOT.jar"
  arguments:
    - "10000"
  sparkConf:
    "spark.kubernetes.local.dirs.tmpfs": "true"
  sparkVersion: "2.4.5-SNAPSHOT"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1024m"
    memory: "512m"
    labels:
      version: 2.4.5-SNAPSHOT
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.5-SNAPSHOT
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"