apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-hostpath
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "seedjeffwan/spark:2.4.5-SNAPSHOT"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.5-SNAPSHOT.jar"
  arguments:
    - "10000"
#  sparkConf:
#    "spark.local.dir": "/tmp/mnt-1,/tmp/mnt-2,/tmp/mnt-3"
  sparkVersion: "2.4.5-SNAPSHOT"
  restartPolicy:
    type: Never
  volumes:
    - name: "spark-local-dir-1"
      hostPath:
        path: "/tmp/mnt-1"
    - name: "spark-local-dir-2"
      hostPath:
        path: "/tmp/mnt-2"
    - name: "spark-local-dir-3"
      hostPath:
        path: "/tmp/mnt-3"
  driver:
    cores: 1
    coreLimit: "1024m"
    memory: "512m"
    labels:
      version: 2.4.5-SNAPSHOT
    serviceAccount: spark
    volumeMounts:
      - name: "spark-local-dir-1"
        mountPath: "/tmp/mnt-1"
      - name: "spark-local-dir-2"
        mountPath: "/tmp/mnt-2"
      - name: "spark-local-dir-3"
        mountPath: "/tmp/mnt-3"
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 2.4.5-SNAPSHOT
    volumeMounts:
      - name: "spark-local-dir-1"
        mountPath: "/tmp/mnt-1"
      - name: "spark-local-dir-2"
        mountPath: "/tmp/mnt-2"
      - name: "spark-local-dir-3"
        mountPath: "/tmp/mnt-3"


# volumeMounts are not there.
# /opt/spark/bin/spark-submit
# --class org.apache.spark.examples.SparkPi
# --master k8s://https://10.100.0.1:443
# --deploy-mode cluster
# --conf spark.kubernetes.namespace=default
# --conf spark.app.name=spark-pi-hostpath
# --conf spark.kubernetes.driver.pod.name=spark-pi-hostpath-driver
# --conf spark.kubernetes.container.image=seedjeffwan/spark:2.4.5-SNAPSHOT
# --conf spark.kubernetes.container.image.pullPolicy=Always
# --conf spark.kubernetes.submission.waitAppCompletion=false
# --conf spark.local.dirs=/tmp/mnt-1,/tmp/mnt-2
# --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=spark-pi-hostpath
# --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true
# --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/submission-id=d04697ad-010a-4ed5-81a9-d0f82403bcdf
# --conf spark.driver.cores=1
# --conf spark.kubernetes.driver.limit.cores=1024m
# --conf spark.driver.memory=512m
# --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark
# --conf spark.kubernetes.driver.label.version=2.4.5-SNAPSHOT
# --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=spark-pi-hostpath
# --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true
# --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/submission-id=d04697ad-010a-4ed5-81a9-d0f82403bcdf
# --conf spark.executor.instances=2
# --conf spark.executor.cores=1
# --conf spark.executor.memory=512m
# --conf spark.kubernetes.executor.label.version=2.4.5-SNAPSHOT
# local:///opt/spark/examples/jars/spark-examples_2.11-2.4.5-SNAPSHOT.jar 10000
