apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: wordcount
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "seedjeffwan/spark:2.4.3"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.JavaWordCount
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.3.jar"
  arguments:
    - /data/out.txt
  sparkVersion: "2.4.3"
  restartPolicy:
    type: Never
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.3
    serviceAccount: spark
    volumeMounts:
      - name: persistent-storage
        mountPath: /data
  executor:
    cores: 1
    instances: 1
    memory: "1g"
    labels:
      version: 2.4.3
    volumeMounts:
      - name: persistent-storage
        mountPath: /data
