---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-history-server-cr
  labels:
    app.kubernetes.io/name: spark-history-server
rules:
- apiGroups: [""]
  resources: ["deployments", "pods"]
  verbs: ["*"]
