apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service-account.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- deployment.yaml
- service.yaml
commonLabels:
  app: spark-history-server
  kustomize.component: spark-history-server
images:
- name: seedjeffwan/spark
  newName: seedjeffwan/spark
  newTag: 3.0.0-SNAPSHOT
# Get S3 directory out.