---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  labels:
    app.kubernetes.io/name: spark-history-server
spec:
  type: ClusterIP
  ports:
  - port: 18080
    protocol: TCP
  selector:
    app.kubernetes.io/name: spark-history-server